import {  Page, Locator} from "playwright/test"
export class BillEntryModel{
  private page: Page;
  accountNumber: Locator;
  accountNumber2: Locator;
  accountNumberinList1stClick: Locator;
  accountNumberinList2ndClick: Locator;
  adjustmentsFromDropdown: Locator;
  amountInputBox: Locator;
  ascendingOrderArrow: Locator;
  balanceForwardFromDropdown: Locator;
  billImagesSuccessfulAlert: Locator;
  billsFirstCellText: Locator;
  chargeItemButton: Locator;
  consumptionInputBox: Locator;
  consumptionSparkLine: Locator;
  consumptionTotal: Locator;
  controlNumber: Locator;
  controlNumber2: Locator;
  controlNumberHeader: Locator;
  currentReadInputBox: Locator;
  cycleStartEndInput: Locator;
  dataEntryLineHeader: Locator;
  dataEntryMeterHeader: Locator;
  dataEntrySaveButton: Locator;
  decendingOrderArrow: Locator;
  deleteBillButton: Locator;
  deleteBillSuccessfulAlert: Locator;
  deleteDataEntryButton: Locator;
  expenseSparkLine: Locator;
  fileUploadButton: Locator;
  fileUploadIcon: Locator;
  HCFUsageProviderSelect: Locator;
  hundredGallonsProviderSelect: Locator;
  lineItemItemNameDropdown: Locator;
  manualBillUploadIcon: Locator;
  manualUploadAccountNumber: Locator;
  manualUploadBill: Locator;
  manualUploadControlNumber: Locator;
  manualUploadSection: Locator;
  meterItemButton: Locator;
  meterItemGridFirstItem: Locator;
  meterNumberInputBox: Locator;
  meterNumberItemSelect: Locator;
  numberOfRowsInBillTable: Locator;
  previousCurrentDateInput: Locator;
  previousCycleEndInput: Locator;
  previousReadInputBox: Locator;
  propertyCodeSearch: Locator;
  providerMeasureDropDown: Locator;
  removeSelectedUploadedFilesButton: Locator;
  removeUploadedFilesButton: Locator;
  saveBillInfo: Locator;
  selectUploadedFileForRemovalCheckbox: Locator;
  sortArrow: Locator;
  sortBills: Locator;
  thousandGallonsProviderSelect: Locator;
  toastNotificationLineDeleted: Locator;
  toastNotificationLineDidNotDeleted: Locator;
  toastNotificationLineSavedNotSuccessful: Locator;
  toastNotificationLineSavedSuccessful: Locator;
  toastNotificationSaveNotSuccessful: Locator;
  toastNotificationSaveSuccessful: Locator;
  uploadFilesConfirmButton: Locator;
  waterResConsumptionProviderSelect: Locator;
  abbyyLiteUploadToggle: Locator;
  meterItemsSection: Locator;

constructor(page: Page, propertyCode: string){

this.page = page;

// this.accountNumber = page.getByRole('cell', { name: '1015-220012304028' });
this.abbyyLiteUploadToggle = page.getByLabel('ABBYY-Lite Upload')
this.accountNumber = page.getByRole('cell', { name: '3012692325' });
this.accountNumber2 = page.getByRole('cell', { name: '3055064819' });
this.accountNumberinList1stClick = page.getByText('Accounts for Town Square at Mark Center IAccount').getByRole('cell').nth(2);
this.accountNumberinList2ndClick = page.getByText('Accounts for Town Square at Mark Center IAccount').getByRole('cell').nth(0);
this.adjustmentsFromDropdown = page.getByRole('option', { name: 'Adjustments' }).first();
this.amountInputBox = page.getByLabel('Amount', { exact: true }).first();
this.ascendingOrderArrow = page.getByText('Bills for 1027-210037313529Control NumberService StartService End').getByTestId('ArrowUpwardIcon').first(); 
this.balanceForwardFromDropdown = page.getByRole('option', { name: 'Balance Forward' }).first();
this.billImagesSuccessfulAlert = page.getByText('Bill images successfully uploaded.');
this.billsFirstCellText = page.locator('#manual_upload_bill_panel_id').getByRole('row').nth(1).getByRole('cell').first();
this.chargeItemButton = page.getByLabel('Enter Charge Items');
this.consumptionInputBox = page.getByLabel('Cons.', { exact: true }).first();
this.consumptionSparkLine = page.getByRole('row', { name: 'Consumption' }).locator('rect').first();
this.consumptionTotal = page.getByText('Meter ItemsMeter').locator('.MuiTypography-root').getByText('Cons');
this.controlNumber = page.getByRole('cell', { name: 'BME24020100457' });
this.controlNumber2 = page.getByRole('cell', { name: 'BMX24072000022' });
// this.controlNumber = page.getByRole('cell', { name: 'BMC24030500206' });
this.controlNumberHeader = page.getByRole('row', { name: 'Control Number Service Start Service End', exact: true }).getByLabel('Control Number');
this.currentReadInputBox = page.getByLabel('Cur. Read', { exact: true }).first();
this.cycleStartEndInput = page.getByRole('textbox', { name: 'Cycle Start' });
this.dataEntryLineHeader = page.getByRole('button', { name: 'Data Entry - Line' });
this.dataEntryMeterHeader = page.getByRole('button', { name: 'Data Entry - Meter' });
this.dataEntrySaveButton = page.getByRole('button', { name: 'Save', exact: true });
this.decendingOrderArrow = page.getByTestId('ArrowDownwardIcon');
this.deleteBillButton = page.getByRole('button', { name: 'Delete Bill', exact: true });
this.deleteBillSuccessfulAlert = page.getByRole('alert');
this.deleteDataEntryButton = page.getByRole('button', { name: 'Delete', exact: true });
this.expenseSparkLine = page.getByRole('row', { name: 'Expense' }).locator('rect').first();
this.fileUploadButton = page.locator('#file-upload');
this.fileUploadIcon = page.locator('#file-upload');
this.HCFUsageProviderSelect = page.getByRole('option', { name: 'HCF Usage' }).first();
this.hundredGallonsProviderSelect = page.getByRole('option', { name: '100 gal Usage' });
this.lineItemItemNameDropdown = page.getByRole('combobox', { name: 'Item Name' });
this.manualBillUploadIcon = page.getByTestId('FileUploadIcon');
this.manualUploadAccountNumber = page.getByRole('cell', { name: '1027-210037313529' });
this.manualUploadBill = page.getByLabel('Manually upload bill');
this.manualUploadControlNumber = page.getByText('Bills for 1027-210037313529Control NumberService StartService End').getByRole('cell').nth(0);
this.manualUploadSection = page.locator('#file-upload');
this.meterItemButton = page.getByLabel('Enter Meter Items');
this.meterItemGridFirstItem = page.locator('#manual_upload_meter_items_panel_id').getByRole('row').nth(1);
this.meterItemsSection = page.getByRole('button', { name: 'Meter Items - Total:' }).first();
this.meterNumberInputBox = page.getByLabel('Meter #');
this.meterNumberItemSelect = page.getByRole('cell', { name: '90619014' });
this.numberOfRowsInBillTable =  page.locator('#manual_upload_bill_panel_id').getByRole('row');
this.previousCurrentDateInput = page.getByRole('textbox', { name: 'Cycle Start' });
this.previousCycleEndInput =  page.getByRole('textbox', { name: 'Cycle End' });
this.previousReadInputBox = page.getByLabel('Prev. Read', { exact: true }).first();
this.propertyCodeSearch = page.getByLabel('Property Code(s)');
this.providerMeasureDropDown = page.getByRole('combobox', { name: 'Provider Measure' });
this.removeSelectedUploadedFilesButton = page.getByRole('button', { name: 'Remove Selected Files' });
this.removeUploadedFilesButton = page.getByLabel('remove', { exact: true });
this.saveBillInfo = page.getByRole('button', { name: 'Save Bill Info', exact: true });
this.selectUploadedFileForRemovalCheckbox = page.getByLabel('Select row');
this.sortArrow = page.getByRole('button', { name: 'Sort' });
this.thousandGallonsProviderSelect = page.getByRole('option', { name: 'Thousand Gallons' });
this.toastNotificationLineDeleted = page.getByText('Meter Item Deleted');
this.toastNotificationLineDidNotDeleted = page.getByText('\'BME24020100457\' Bills assigned to a billing instance cannot be modified.');
this.toastNotificationLineSavedNotSuccessful = page.getByText('\'BME24020100457\' Bills assigned to a billing instance cannot be modified.');
this.toastNotificationLineSavedSuccessful = page.getByText('Line Item Saved');
this.toastNotificationSaveNotSuccessful= page.getByText('cannot be modified').first();
this.toastNotificationSaveSuccessful= page.getByText('Meter Item Saved Successfully').first();
this.uploadFilesConfirmButton = page.getByRole('button', { name: 'Upload', exact: true });
this.waterResConsumptionProviderSelect = page.getByRole('option', { name: 'WATER RES CONSUMPTION' });

}}



